### ISSUE TITLE
Idée : Obtenir un shell stable après injection de payload

### ISSUE THREAD

**Issue by thomasarmel** [haysberg/random-veille#69]
Faire un tuto pour expliquer comment stabiliser le shell après une payload injection, façon:

![image](https://github.com/haysberg/random-veille/assets/24313857/60259fdd-2b55-48d5-9223-4a3b7ef31719)

(permet par exemple de faire ^C)

You have to type "screen", and Enter, when you are asked for terminal type

Source: https://0xdf.gitlab.io/2023/08/12/htb-busqueda.html#shell-as-root

**Comment by haysberg** [comment]
Bonne idée. 
J'ai pas encore les connaissances pour aider mais je vais essayer de voir si on peut pas trouver ça. Sinon je peux toujours essayer de faire une petite explication basée sur quelques cours de HTBA.

Si quelqu'un se sent chaud pour écrire une page comme ça qu'il se manifeste !

**Comment by MonsieurCo** [comment]
yes pk pas mais dans qq jours pour moi

**Comment by thomasarmel** [comment]
@MonsieurCo comme tu veux sinon je m'en occupe.
Mon idée c'était d'expliquer les commandes une par une en mettant des screenshots au fur et à mesure

**Comment by haysberg** [comment]
Au pire, fait une merge request et on te fera un retour.
Pour les screens, tu peux utiliser les fonctions de Docusaurus pour mettre en forme la console : 
https://docusaurus.io/docs/markdown-features/code-blocks
