### ISSUE TITLE
Idée : Une page pour payer moins cher

### ISSUE THREAD

**Issue by haysberg** [haysberg/random-veille#76]
J'aimerais bien qu'on fasse une page avec pas mal de tips pour réussir à payer moins cher pas mal de trucs.

Pour l'instant j'aimerais mettre :
- La liste des aides auxquels ont droit les étudiants suivant leurs situations
- Les aides au permis (en voiture simone si je dis pas de bêtises)
- toogoodtogo / les restos du coeur
- dealabs ? pas sûr

Je suis toujours en recherche d'idées après...

**Comment by thomasarmel** [comment]
De mon vécu personnel on pourrait aussi rajouter:

- Les astuces pour partir à l'international (genre quel dossier, qui contacter...) avec toues les aides possibles
- Comment bien gérer l'administratif de la fac
