### ISSUE TITLE
OSCP

### ISSUE THREAD

**Issue by thomasarmel** [haysberg/random-veille#79]
Est-ce qu'on pourrait ajouter l'OSCP dans les certifs, même si c'est un truc pro ?

**Comment by haysberg** [comment]
C'est toutes des trucs pro.
Je pourrais la mentionner, mais ça serait surtout pour dire qu'elle est beaucoup trop chère pour des étudiants et qu'en terme de connaissances au final on peut apprendre autant avec les autres certifs.

**Comment by thomasarmel** [comment]
Ouais faut arriver à se la faire payer par sa boîte au final 😆

**Comment by haysberg** [comment]
Oui, inaccessible à moins d'avoir un daron riche donc je me permets pas de le mettre dans le wiki.
